import Head from "next/head";
import styles from "../styles/Home.module.css";
import Homepage from "../components/Homepage";

export default function Home() {
    return (
        <div className="width-full">
            <Head>
                <title>Destress</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/assets/braindark.svg" />
            </Head>

            <Homepage />
        </div>
    );
}
